<meta name="format-detection" content="telephone=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<link href="/img/favicon.png" rel="apple-touch-icon-precomposed">
<link href="/img/favicon.png" rel="shortcut icon" type="image/png">
<meta name="author" content="">
<meta name="keywords" content="">
<meta name="description" content="">
<link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="/fonts/Linearicons/Font/demo-files/demo.css">
<link rel="preconnect" href="https://fonts.gstatic.com/">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Jost:400,500,600,700&amp;display=swap&amp;ver=1607580870">
<link rel="stylesheet" href="/plugins/bootstrap4/css/bootstrap.min.css">
<link rel="stylesheet" href="/plugins/owl-carousel/assets/owl.carousel.css">
<link rel="stylesheet" href="/plugins/slick/slick/slick.css">
<link rel="stylesheet" href="/plugins/lightGallery/dist/css/lightgallery.min.css">
<link rel="stylesheet" href="/plugins/jquery-bar-rating/dist/themes/fontawesome-stars.css">
<link rel="stylesheet" href="/plugins/select2/dist/css/select2.min.css">
<link rel="stylesheet" href="/plugins/lightGallery/dist/css/lightgallery.min.css">
<link rel="stylesheet" href="/plugins/noUiSlider/nouislider.css">
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/home-1.css">